OPTIONS SYMBOLGEN=YES;

*Equivalence Test 2;

%MACRO EQVTEST2(DSNAME, VARNAME);
PROC GLM DATA=&DSNAME;
  CLASS SEQUENCE TREATMENT SUBJECT PERIOD;
  MODEL &VARNAME = SEQUENCE SUBJECT(SEQUENCE) PERIOD TREATMENT;
  RANDOM SUBJECT(SEQUENCE)/TEST;
  LSMEANS TREATMENT/PDIFF=CONTROL('R') CL ALPHA=0.1;
RUN;


%MEND EQVTEST2;

* Autual Run;

DATA TAD;
  INFILE 'c:\Users\mdlhs\asancpt\BEreport\sas\NCAResult4BE.csv' FIRSTOBS=2 DLM="," ;
  INPUT SUBJECT $ SEQUENCE $ PERIOD $ TREATMENT $ AUClast Cmax Tmax;
  LNCMAX = LOG(Cmax); 
  LNAUCL = LOG(AUClast );

PROC PRINT; RUN;

*Equivalence Test 2;

%EQVTEST2(TAD, LNCMAX);
%EQVTEST2(TAD, LNAUCL);
