OPTIONS SYMBOLGEN=YES;

*Equivalence Test 2;

%MACRO EQVTEST2(DSNAME, VARNAME);
PROC GLM DATA=&DSNAME;
  CLASS ADM SEQUENCE TREATMENT SUBJECT PERIOD;
  MODEL &VARNAME = ADM SEQUENCE SUBJECT(ADM*SEQUENCE) PERIOD TREATMENT;
  RANDOM ADM SUBJECT(ADM*SEQUENCE)/TEST;
RUN;

PROC MIXED DATA=&DSNAME;
  CLASS ADM SEQUENCE TREATMENT SUBJECT PERIOD;
  MODEL &VARNAME = SEQUENCE PERIOD TREATMENT;
  RANDOM ADM SUBJECT(ADM*SEQUENCE);
  ESTIMATE 'T - R' TREATMENT -1 1 /CL ALPHA=0.1; 
  ODS OUTPUT ESTIMATES=ESTIM COVPARMS=COVPAR;
RUN;

DATA COVPAR;
  SET COVPAR;
  IF CovParm = 'Residual' THEN CALL SYMPUT('MSE', Estimate);

DATA ESTIM;
  SET ESTIM;
  MSE = &MSE;
  PE = EXP(Estimate);
  LL = EXP(Lower);
  UL = EXP(Upper);
PROC PRINT Data=ESTIM; RUN;

%MEND EQVTEST2;

* Autual Run;

DATA TAD;
  INFILE 'file' FIRSTOBS=2 DLM="," ;
  INPUT SUBJECT $ ADM $ TREATMENT $ SEQUENCE $ PERIOD $ Tmax Cmax AUClast;
  LNCMAX = LOG(Cmax); 
  LNAUCL = LOG(AUClast );

PROC PRINT; RUN;

DATA ADM1;
  SET TAD;
  IF ADM='1';
PROC PRINT DATA=ADM1; RUN;

DATA ADM2;
  SET TAD;
  IF ADM='2';
PROC PRINT DATA=ADM2; RUN;

*Equivalence Test 2;

%EQVTEST2(TAD, LNCMAX);
%EQVTEST2(TAD, LNAUCL);
